"""External rendered browser boundary: no session export or hidden API payloads."""

from typing import Literal, Protocol

ExecutionLimit = Literal["requests", "pages", "time"]


class BrowserUnavailable(Exception):
    pass


class BrowserBudgetExceeded(Exception):
    def __init__(self, limit: ExecutionLimit):
        super().__init__(limit)
        self.limit = limit


class RenderedBrowser(Protocol):
    @property
    def available(self) -> bool: ...

    async def start(self, *, max_requests: int) -> None: ...
    async def bring_to_front(self) -> None: ...
    async def navigate(self, url: str) -> None: ...
    async def snapshot(self) -> tuple[str, str, int]: ...
    async def weibo_cookies(self) -> dict[str, str]: ...
    async def freeze(self) -> None: ...
    async def show(self) -> None: ...
    async def close_page(self) -> None: ...
    async def shutdown(self) -> None: ...
